#!/bin/bash

# dump velodyne packets for ART robot autonomous vehicle
# $Id: vdump 8892 2009-10-24 15:13:57Z joq $

if [ x$1 = x ]
then	echo -e "usage:\t`basename $0` file-prefix [ interface ]"
	echo -e "\n\tfile-prefix is completed with a three-digit number"
	echo -e "\tinterface default is 'eth1'\n"
	exit 9
fi

IF=${2:-eth1}
ID=`id -un`

echo "acquiring packets on $IF for user $ID; press ^C when done"

sudo /usr/sbin/tcpdump -i $IF -Z $ID -s 0 -C 100 -W 999 -w $1
